services:
  relay:
    image: gofeatureflag/go-feature-flag:latest
    ports:
      - "1031:1031"
    volumes:
      - ./flags:/goff/flags
      - ./goff-proxy.yaml:/goff/goff-proxy.yaml
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "1324:80"
    environment:
      - APP_ENV=local
    depends_on:
      - relay
    restart: unless-stopped

networks:
  default:
    name: bettercity_local
    external: true
